development:
  adapter: postgresql
  encoding: utf8
  database: openT_development
  username: root
  password: root
  template: template0 # Required for UTF8 encoding
 
test:
  adapter: postgresql
  encoding: utf8
  database: openT_test
  username: 
  password: 
  template: template0 # Required for UTF8 encoding
 
production:
  adapter: postgresql
  encoding: utf8
  database: openT_production
  username: 
  password: 
  template: template0 # Required for UTF8 encoding