development: &development
  ws_url: "http://localhost:4000"
  ps_url: "http://localhost:4000"
  email: matheustardivo@gmail.com
  token: "a1951ac04115012fabb660334b97cc6e"

test:
  <<: *development

production:
  ws_url: "https://ws.pagseguro.uol.com.br"
  ps_url: "https://pagseguro.uol.com.br"
  email: matheustardivo@gmail.com
  token: "tokenGeradoPeloPagseguro"