development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/events/gift/success"
  email: kleberpinel@gmail.com

test:
  <<: *development

production:
  authenticity_token: 2E09EF8D396E4BCC8B4B68DA30ED7004
  email: kleberpinel@gmail.com
  return_to: "/events/gift/success"